---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: harrijin-final-redis-data
    labels:
        username: harrijin
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: rbd
    resources:
        requests:
            storage: 1Gi
