---
apiVersion: v1
kind: Service
metadata:
    name: harrijin-final-api
    labels:
        username: harrijin
spec:
    type: ClusterIP
    selector:
        app: harrijin-final-api
    ports:
      - name: harrijin-final-api
        port: 5000
        targetPort: 5000