---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: harrijin-final-worker-deployment
    labels:
        username: harrijin
spec:
    replicas: 2
    selector:
        matchLabels:
            app: harrijin-final-worker
    template:
        metadata:
            labels:
                username: harrijin
                app: harrijin-final-worker
        spec:
            containers:
              - name: harrijin-final-worker
                image: harrijin/pandemic-mobility-wrk:latest
                imagePullPolicy: Always
                env:
                  - name: REDIS_IP
                    value: "10.96.187.10"
                  - name: WORKER_IP
                    valueFrom:
                        fieldRef:
                            fieldPath: status.podIP
                ports:
                  - containerPort: 5000
