---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: harrijin-test-worker-deployment
    labels:
        username: harrijin
        env: test
spec:
    replicas: 2
    selector:
        matchLabels:
            app: harrijin-test-worker
    template:
        metadata:
            labels:
                username: harrijin
                env: test
                app: harrijin-test-worker
        spec:
            containers:
              - name: harrijin-test-worker-pod
                image: harrijin/flask:latest
                command: ["python3"]
                args: ["worker.py"]
                env:
                  - name: REDIS_IP
                    value: "10.101.245.196"
                  - name: WORKER_IP
                    valueFrom:
                        fieldRef:
                            fieldPath: status.podIP
                ports:
                  - containerPort: 5000
